### PR TITLE
Pass DOM element instead of selector if you want.

### PR DESCRIPTION
**Pull request by ryanscottaudio**
Pass DOM element instead of selector if you want.

### CODE REVIEW

**Comment by angusfretwell** [comment]
I like this idea; what if instead of a single element, you could pass an array of elements? What do you think?

**Comment by ryanscottaudio** [comment]
thats cool too, let me add that!

**Comment by angusfretwell** [comment]
Thanks Ryan. Could you please also update the readme to reflect your changes and I'll merge this in!

**Comment by ryanscottaudio** [comment]
shoot, i deleted our fork. let me make another one

**Pull request closed without merging**
